### PR TITLE
ENHANCEMENT Add campaign description field

### PR DESCRIPTION
**Pull request by phalkunz**

### CODE REVIEW

**Comment by sminnee** [comment]
@phalkunz is the campaign description shown anywhere? did Paul C have a view on where it would be appropriate to include?

**Comment by flamerohr** [comment]
@clarkepaul would you be able to verify?

**Comment by clarkepaul** [comment]
The description field is to be added to the settings area of the campaign. This was to provide more context as to whats the campaigns for:
eg. Due date, overview of schedule of work, who are the editors...
Adding the description field was a partially temporary solution in place of the more complex fields which are more of a long term goal.

**Comment by clarkepaul** [comment]
No description needed in the details view, or in the campaign list view as there is more important info planned for those screens.

**Comment by flamerohr** [comment]
Ok cool, please update the Acceptance Criteria and/or tasks next time, thanks!

**Comment by clarkepaul** [comment]
true missed that

**Comment by flamerohr** [comment]
@phalkunz unit tests are referencing the old "Description" field name, rather than the new "Details" field name

**Pull request merged**
