### PR TITLE
FIX Typo in CSS selector breaking behat tests

### PR DESCRIPTION
**Pull request by robbieaverill**

### CODE REVIEW

**Comment by robbieaverill** [comment]
Damn, it's still failing on the "press Remove button" step

**Comment by tractorcow** [comment]
I'm looking at this too, just fixed https://github.com/silverstripe/silverstripe-campaign-admin/pull/98

**Comment by tractorcow** [comment]
Cause https://github.com/silverstripe/silverstripe-admin/pull/470

**Comment by tractorcow** [comment]
New issue https://github.com/silverstripe/silverstripe-asset-admin/issues/774

**Comment by robbieaverill** [comment]
Superseded, closing

**Pull request closed without merging**
