### PR TITLE
FIX Add links to userhelp

### PR DESCRIPTION
**Pull request by emteknetnz**
Implementation of https://github.com/silverstripe/silverstripe-campaign-admin/issues/127

See comment https://github.com/silverstripe/silverstripe-campaign-admin/issues/127#issuecomment-522394784

Links open in a new tab

Looks like this (reduced screen width)

image

### CODE REVIEW

**Comment by emteknetnz** [comment]
Scrutinzer error is inability composer getting confused about what to install because this module has `"silverstripe/framework": "^4.5",` in `composer.json`, so it attempts to install framework `4.n`, meanwhiel this campaign-admin branch, `1.x-dev` wants to installed `4.x-dev`

Travis does not have this issue since `.travis.yml` will install `silverstripe/recipe-cms:4.x-dev`

The scrutinizer failed build doesn't really affect the validity of the code added

If anyone is really bothered I can redo this work on `1.6` instead.  Let me know if you need this one, or if it's fine as is.

**Comment by clarkepaul** [comment]
Thanks @emteknetnz ! Long overdue

**Comment by emteknetnz** [comment]
I've rebased this on top of 1.6.  branch name `pulls/1/infoscreen-links` is misleading, should really be `pulls/1.6/infoscreen-links`

**Comment by robbieaverill** [comment]
Can you rebase onto 1? This is not a bug fix so we can't merge it into a patch release branch

**Pull request merged**
