### PR TITLE
Update AddToCampaignHandler.php

### PR DESCRIPTION
**Pull request by mxmclaudel**
Add to campaign handler should only not show campaigns that are inferred.

### CODE REVIEW

**Comment by mxmclaudel** [comment]
Hi,

I'm slightly confused by the pull request process (I'm fairly new to the contribution process). The default branch is 1, which is behind master. So I don't know which branch this should be merged with... Happy to change if needed.
Thanks

**Comment by mxmclaudel** [comment]
fixes #148

**Comment by robbieaverill** [comment]
@mxmclaudel thanks for the pull request. FYI, the `1` branch is for the next minor release of SilverStripe 4 (e.g. 4.5.x). The master branch is for SilverStripe 5.x, which is why it's ahead of the 1 branch

**Comment by mxmclaudel** [comment]
@robbieaverill Thanks for the clarification. I've created a second PR for branch 1 as well.

**Pull request closed without merging**
